// Generated by scripts/blog-images.mjs -- do not edit by hand.
// Pixel sizes of the images under public/blog, so next/image can reserve
// their space before they load. An image missing from here still renders,
// as a plain <img>, without the layout reservation.
export const BLOG_IMAGE_SIZES: Record<string, { width: number; height: number }> = {
  "/blog/how-to-add-link-in-instagram-bio/link-editor.webp": { width: 1154, height: 2234 },
  "/blog/how-to-add-link-in-instagram-bio/profile-phone.webp": { width: 780, height: 1688 },
  "/blog/how-to-add-link-in-instagram-bio/share-qr.webp": { width: 652, height: 852 },
  "/blog/link-in-bio-for-local-shop/location-picker.webp": { width: 1056, height: 412 },
  "/blog/link-in-bio-for-local-shop/products.webp": { width: 716, height: 1210 },
  "/blog/link-in-bio-for-local-shop/purpose.webp": { width: 1154, height: 1422 },
  "/blog/link-in-bio-for-local-shop/shop-profile.webp": { width: 780, height: 1988 },
  "/blog/whatsapp-link-in-bio/order-button.webp": { width: 716, height: 1210 },
  "/blog/whatsapp-link-in-bio/whatsapp-dialog.webp": { width: 888, height: 724 },
};
