import type { CreatorProfile } from "@/lib/types";

export const demoProfile: CreatorProfile = {
  username: "parth",
  initials: "PB",
  displayName: "Parth",
  greeting: "Hey, I’m",
  headline: "I make useful",
  headlineAccent: "things.",
  eyebrow: "Designer · Developer · Tinkerer",
  bio: "A hand-picked trail of projects, field notes, and tools from my corner of the internet.",
  socials: [
    { platform: "GitHub", url: "https://github.com/parthbhodia" },
    { platform: "LinkedIn", url: "https://www.linkedin.com" },
    { platform: "X / Twitter", url: "https://x.com" },
  ],
  links: [
    {
      id: "project",
      index: "01",
      title: "Latest side-project",
      subtitle: "An open-source experiment for calmer developer workflows.",
      url: "https://github.com/parthbhodia",
      tags: ["project", "portfolio", "developer", "open source", "tools"],
      visits: 142,
      color: "#c9ef69",
    },
    {
      id: "notes",
      index: "02",
      title: "Architecture field notes",
      subtitle: "Practical observations on building systems that hold up.",
      url: "https://github.com/parthbhodia",
      tags: ["writing", "architecture", "engineering", "guide"],
      visits: 89,
      color: "#ffb4d0",
    },
    {
      id: "stack",
      index: "03",
      title: "The creator stack",
      subtitle: "A living shortlist of apps, resources, and tiny discoveries.",
      url: "https://github.com/parthbhodia",
      tags: ["resources", "creator", "tools", "newsletter"],
      visits: 314,
      color: "#9ed6ff",
    },
  ],
  referrals: [
    {
      id: "lyft",
      provider: "Lyft",
      perk: "$15 off your first ride",
      code: "LYFTFREE15",
      url: "https://www.lyft.com",
      tags: ["ride", "travel", "transport", "coupon"],
      color: "#e8347d",
    },
    {
      id: "uber",
      provider: "Uber",
      perk: "Free delivery on 3 orders",
      code: "UBERPERK2026",
      url: "https://www.uber.com",
      tags: ["food", "delivery", "ride", "coupon"],
      color: "#20221f",
    },
    {
      id: "chase",
      provider: "Chase Sapphire",
      perk: "60,000 bonus points offer",
      code: null,
      url: "https://www.chase.com",
      tags: ["card", "finance", "points", "travel"],
      color: "#3659d9",
    },
  ],
};
