import type { CreatorProfile } from "@/lib/types";

export type ExampleMediaEmbed = {
  id: number;
  title: string;
  provider: string;
  url: string;
  layout: string;
};

export type ExampleProduct = {
  id: number;
  title: string;
  description: string;
  price_amount: number | string | null;
  currency: string;
  category: string;
  badge: string | null;
  image_path: string | null;
  destination_url: string;
  cta_label: string;
  is_featured: boolean;
};

export type ExampleProfile = {
  slug: string;
  role: string;
  template: "field-notes" | "after-dark" | "soft-studio";
  profile: CreatorProfile;
  mediaEmbeds?: ExampleMediaEmbed[];
  products?: ExampleProduct[];
};

export const exampleProfiles: ExampleProfile[] = [
  {
    slug: "nova-sounds",
    role: "Musician",
    template: "after-dark",
    mediaEmbeds: [
      {
        id: 1,
        title: "Midnight Signal",
        provider: "spotify",
        url: "https://open.spotify.com/track/11dFghVXANMlKmJXsNCbNl",
        layout: "player",
      },
    ],
    profile: {
      username: "nova-sounds",
      initials: "NS",
      displayName: "Nova",
      greeting: "Hey, I’m",
      headline: "New songs, live dates, and",
      headlineAccent: "the next drop.",
      eyebrow: "Indie · Electronic · Touring",
      bio: "Listen first, then grab tickets, merch, and the mailing list for early access.",
      socials: [
        { platform: "Instagram", url: "https://instagram.com" },
        { platform: "TikTok", url: "https://tiktok.com" },
        { platform: "YouTube", url: "https://youtube.com" },
      ],
      links: [
        {
          id: "nova-1",
          index: "01",
          title: "Tour tickets",
          subtitle: "Spring dates across the East Coast.",
          url: "https://bandcamp.com",
          tags: ["tour", "tickets"],
          visits: 2104,
          color: "#9ed6ff",
          featured: true,
        },
        {
          id: "nova-2",
          index: "02",
          title: "Merch drop",
          subtitle: "Limited run tees and posters.",
          url: "https://shopify.com",
          tags: ["merch", "shop"],
          visits: 980,
          color: "#ffb4d0",
        },
        {
          id: "nova-3",
          index: "03",
          title: "Join the mailing list",
          subtitle: "Early access to drops and tour cities.",
          url: "https://example.com",
          tags: ["email", "list"],
          visits: 640,
          color: "#dfff70",
        },
      ],
      referrals: [
        {
          id: "nova-ref",
          provider: "DistroKid",
          perk: "Upload unlimited music for a year",
          code: "NOVA10",
          url: "https://distrokid.com",
          tags: ["music", "distribution"],
          color: "#ff5c39",
        },
      ],
    },
  },
  {
    slug: "rio-coach",
    role: "Coach",
    template: "field-notes",
    profile: {
      username: "rio-coach",
      initials: "RC",
      displayName: "Rio",
      greeting: "I’m",
      headline: "I help founders ship with",
      headlineAccent: "clearer focus.",
      eyebrow: "Operator coach · Async first",
      bio: "Office hours, a free weekly note, and the operating templates I use with founders.",
      socials: [
        { platform: "LinkedIn", url: "https://linkedin.com" },
        { platform: "X", url: "https://x.com" },
        { platform: "YouTube", url: "https://youtube.com" },
      ],
      links: [
        {
          id: "rio-1",
          index: "01",
          title: "Book a clarity session",
          subtitle: "45 minutes. One bottleneck. A written plan after.",
          url: "https://cal.com/rio/clarity",
          tags: ["coaching", "booking"],
          visits: 1670,
          color: "#c9ef69",
          featured: true,
        },
        {
          id: "rio-2",
          index: "02",
          title: "Free weekly operator note",
          subtitle: "Short, practical, no fluff.",
          url: "https://substack.com",
          tags: ["newsletter", "ops"],
          visits: 2890,
          color: "#9ed6ff",
        },
        {
          id: "rio-3",
          index: "03",
          title: "Founder OS template",
          subtitle: "The Notion system behind my coaching calls.",
          url: "https://gumroad.com",
          tags: ["template", "notion"],
          visits: 1240,
          color: "#ffd166",
        },
      ],
      referrals: [
        {
          id: "rio-ref",
          provider: "Superhuman",
          perk: "Try the inbox I recommend to clients",
          code: null,
          url: "https://superhuman.com",
          tags: ["email", "productivity"],
          color: "#4a3aff",
        },
      ],
    },
  },
  {
    slug: "maya-makes",
    role: "Creator",
    template: "soft-studio",
    profile: {
      username: "maya-makes",
      initials: "MM",
      displayName: "Maya",
      greeting: "Hi, I’m",
      headline: "I turn tiny ideas into",
      headlineAccent: "bright things.",
      eyebrow: "Illustrator · Video maker",
      bio: "Sketchbook tours, cheerful downloads, and the tools behind my weekly studio practice.",
      socials: [
        { platform: "Instagram", url: "https://instagram.com" },
        { platform: "YouTube", url: "https://youtube.com" },
        { platform: "TikTok", url: "https://tiktok.com" },
      ],
      links: [
        {
          id: "maya-1",
          index: "01",
          title: "Watch the latest studio diary",
          subtitle: "A quiet week of drawing, filming, and trying again.",
          url: "https://www.youtube.com/watch?v=aqz-KE-bpKQ",
          tags: ["video", "studio", "youtube"],
          visits: 1842,
          color: "#ffb7d0",
          featured: true,
        },
        {
          id: "maya-2",
          index: "02",
          title: "Download my brush pack",
          subtitle: "Twelve textured brushes for playful lettering.",
          url: "https://gumroad.com",
          tags: ["brushes", "download", "shop"],
          visits: 964,
          color: "#d9c7ff",
        },
        {
          id: "maya-3",
          index: "03",
          title: "Print shop",
          subtitle: "Limited risograph prints shipping this month.",
          url: "https://gumroad.com",
          tags: ["prints", "shop"],
          visits: 512,
          color: "#ffd166",
        },
      ],
      referrals: [
        {
          id: "maya-ref",
          provider: "Skillshare",
          perk: "Try one month of creative classes",
          code: "MAYA1",
          url: "https://skillshare.com",
          tags: ["classes", "creative"],
          color: "#7d45df",
        },
      ],
    },
  },
  {
    slug: "sam-builds",
    role: "Freelancer",
    template: "field-notes",
    profile: {
      username: "sam-builds",
      initials: "SB",
      displayName: "Sam",
      greeting: "Hey, I’m",
      headline: "I design calmer",
      headlineAccent: "products.",
      eyebrow: "Independent product designer",
      bio: "Selected launches, practical product notes, and a straightforward way to work together.",
      socials: [
        { platform: "LinkedIn", url: "https://linkedin.com" },
        { platform: "Dribbble", url: "https://dribbble.com" },
        { platform: "GitHub", url: "https://github.com" },
      ],
      links: [
        {
          id: "sam-1",
          index: "01",
          title: "Selected client work",
          subtitle: "Three launches, the decisions behind them, and what changed.",
          url: "https://dribbble.com",
          tags: ["portfolio", "client work", "case study"],
          visits: 2210,
          color: "#c9ef69",
          featured: true,
        },
        {
          id: "sam-2",
          index: "02",
          title: "Book a 30-minute intro",
          subtitle: "For product design, audits, and focused advisory work.",
          url: "https://cal.com",
          tags: ["booking", "work", "consulting"],
          visits: 743,
          color: "#9ed6ff",
        },
        {
          id: "sam-3",
          index: "03",
          title: "Product critique notes",
          subtitle: "Free writing on shipping calmer interfaces.",
          url: "https://substack.com",
          tags: ["writing", "product"],
          visits: 1180,
          color: "#ffd166",
        },
      ],
      referrals: [
        {
          id: "sam-ref",
          provider: "Notion",
          perk: "The project handoff system I use with every client",
          code: "SAMBUILDS",
          url: "https://notion.so",
          tags: ["notion", "template", "workflow"],
          color: "#20221f",
        },
      ],
    },
  },
  {
    slug: "dani-deals",
    role: "Referral curator",
    template: "after-dark",
    profile: {
      username: "dani-deals",
      initials: "DD",
      displayName: "Dani",
      greeting: "I’m",
      headline: "I test the deal before I",
      headlineAccent: "share it.",
      eyebrow: "Travel · Tech · Worthwhile perks",
      bio: "A small, maintained list of offers I actually use—with expiry notes and no mystery links.",
      socials: [
        { platform: "Instagram", url: "https://instagram.com" },
        { platform: "Threads", url: "https://threads.net" },
        { platform: "YouTube", url: "https://youtube.com" },
      ],
      links: [
        {
          id: "dani-1",
          index: "01",
          title: "How I evaluate a referral offer",
          subtitle: "The five checks I make before anything lands here.",
          url: "https://medium.com",
          tags: ["guide", "trust", "referrals"],
          visits: 1560,
          color: "#b9ff66",
          featured: true,
        },
        {
          id: "dani-2",
          index: "02",
          title: "This month’s shortlist",
          subtitle: "Three offers still worth using before they expire.",
          url: "https://notion.so",
          tags: ["list", "deals"],
          visits: 890,
          color: "#9ed6ff",
        },
      ],
      referrals: [
        {
          id: "dani-ref-1",
          provider: "Airalo",
          perk: "$3 off your first travel eSIM",
          code: "DANI3",
          url: "https://airalo.com",
          tags: ["travel", "esim", "coupon"],
          color: "#6d54d8",
        },
        {
          id: "dani-ref-2",
          provider: "Wise",
          perk: "Fee-free international transfer",
          code: "DANIWISE",
          url: "https://wise.com",
          tags: ["travel", "money", "transfer"],
          color: "#2e7d59",
        },
      ],
    },
  },
  {
    slug: "lea-shop",
    role: "Shop owner",
    template: "soft-studio",
    products: [
      {
        id: 1,
        title: "Speckled mug",
        description: "Hand-thrown stoneware. Holds 12 oz.",
        price_amount: 48,
        currency: "USD",
        category: "merch",
        badge: "New",
        image_path: null,
        destination_url: "https://shopify.com",
        cta_label: "Buy now",
        is_featured: true,
      },
      {
        id: 2,
        title: "One-off vase",
        description: "Kiln drop — only two left.",
        price_amount: 120,
        currency: "USD",
        category: "merch",
        badge: "Limited",
        image_path: null,
        destination_url: "https://shopify.com",
        cta_label: "Shop vase",
        is_featured: false,
      },
      {
        id: 3,
        title: "Studio visit",
        description: "Saturday morning tour for small groups.",
        price_amount: 25,
        currency: "USD",
        category: "service",
        badge: null,
        image_path: null,
        destination_url: "https://cal.com/lea/studio",
        cta_label: "Book visit",
        is_featured: false,
      },
    ],
    profile: {
      username: "lea-shop",
      initials: "LS",
      displayName: "Lea",
      greeting: "Hi, I’m",
      headline: "Handmade goods with a",
      headlineAccent: "soft finish.",
      eyebrow: "Ceramics · Home · Slow drops",
      bio: "New kiln drops, restock alerts, and the story behind each piece.",
      socials: [
        { platform: "Instagram", url: "https://instagram.com" },
        { platform: "Pinterest", url: "https://pinterest.com" },
        { platform: "TikTok", url: "https://tiktok.com" },
      ],
      links: [
        {
          id: "lea-1",
          index: "01",
          title: "Shop the spring drop",
          subtitle: "Open the Shop tab for mugs, bowls, and vases.",
          url: "https://shopify.com",
          tags: ["shop", "ceramics"],
          visits: 3120,
          color: "#f0c5e1",
          featured: true,
        },
        {
          id: "lea-2",
          index: "02",
          title: "Join restock alerts",
          subtitle: "Get first look when favorites return.",
          url: "https://beehiiv.com",
          tags: ["newsletter", "restock"],
          visits: 1540,
          color: "#d9c7ff",
        },
        {
          id: "lea-3",
          index: "03",
          title: "Studio visit booking",
          subtitle: "Small group tours on Saturday mornings.",
          url: "https://cal.com/lea/studio",
          tags: ["studio", "visit"],
          visits: 420,
          color: "#ffd166",
        },
      ],
      referrals: [
        {
          id: "lea-ref",
          provider: "Packhelp",
          perk: "Custom packaging for small brands",
          code: "LEA10",
          url: "https://packhelp.com",
          tags: ["packaging", "brand"],
          color: "#9b3c78",
        },
      ],
    },
  },
  {
    slug: "harbor-whatsapp",
    role: "WhatsApp Business",
    template: "soft-studio",
    profile: {
      username: "harbor-whatsapp",
      initials: "HC",
      displayName: "Harbor Café",
      greeting: "Welcome to",
      headline: "Coffee, lunch, and quick orders through",
      headlineAccent: "WhatsApp.",
      eyebrow: "Neighborhood café · Open daily",
      bio: "Browse today’s menu, message the café, place an order, or get directions from one simple page.",
      socials: [
        {
          platform: "WhatsApp Business",
          url: "https://wa.me/15551234567?text=Hi%20Harbor%20Cafe",
        },
        { platform: "Instagram", url: "https://instagram.com" },
        { platform: "Website", url: "https://example.com" },
      ],
      links: [
        {
          id: "harbor-1",
          index: "01",
          title: "Chat with us on WhatsApp",
          subtitle: "Questions, pickup orders, and daily specials.",
          url: "https://wa.me/15551234567?text=Hi%20Harbor%20Cafe",
          tags: ["whatsapp", "contact", "order"],
          visits: 1480,
          color: "#25d366",
          featured: true,
        },
        {
          id: "harbor-2",
          index: "02",
          title: "View today’s menu",
          subtitle: "Coffee, breakfast, lunch, and seasonal specials.",
          url: "https://example.com/menu",
          tags: ["menu", "catalog"],
          visits: 960,
          color: "#f0c5e1",
        },
        {
          id: "harbor-3",
          index: "03",
          title: "Get directions",
          subtitle: "Open the café location in Maps.",
          url: "https://maps.google.com",
          tags: ["location", "directions"],
          visits: 530,
          color: "#ffd166",
        },
      ],
      referrals: [],
    },
  },
  {
    slug: "northstar-business",
    role: "Business links",
    template: "field-notes",
    profile: {
      username: "northstar-business",
      initials: "NS",
      displayName: "Northstar Studio",
      greeting: "We’re",
      headline: "One clear place for every",
      headlineAccent: "business action.",
      eyebrow: "Strategy · Design · New York",
      bio: "Explore services, book a consultation, review recent work, or contact the team directly.",
      socials: [
        { platform: "LinkedIn", url: "https://linkedin.com" },
        {
          platform: "WhatsApp Business",
          url: "https://wa.me/15551234567?text=Hi%20Northstar",
        },
        { platform: "Website", url: "https://example.com" },
      ],
      links: [
        {
          id: "northstar-1",
          index: "01",
          title: "Explore our services",
          subtitle: "Brand strategy, web design, and focused advisory.",
          url: "https://example.com/services",
          tags: ["services", "business"],
          visits: 1850,
          color: "#c9ef69",
          featured: true,
        },
        {
          id: "northstar-2",
          index: "02",
          title: "Book an appointment",
          subtitle: "Choose a convenient time for a discovery call.",
          url: "https://calendly.com",
          tags: ["booking", "consultation"],
          visits: 1010,
          color: "#9ed6ff",
        },
        {
          id: "northstar-3",
          index: "03",
          title: "Read customer reviews",
          subtitle: "See recent client feedback and project outcomes.",
          url: "https://www.google.com/maps",
          tags: ["reviews", "proof"],
          visits: 740,
          color: "#ffd166",
        },
        {
          id: "northstar-4",
          index: "04",
          title: "Chat with us on WhatsApp",
          subtitle: "Ask a question or request a quick estimate.",
          url: "https://wa.me/15551234567?text=Hi%20Northstar",
          tags: ["whatsapp", "contact"],
          visits: 620,
          color: "#25d366",
        },
      ],
      referrals: [],
    },
  }
];

export const exampleProfileBySlug = new Map(
  exampleProfiles.map((example) => [example.slug, example]),
);
