// Turns raw screenshots into the WebP files the blog serves and rewrites the
// size manifest next/image needs.
//
//   node scripts/blog-images.mjs <input-dir>
//
// Every PNG/JPEG under <input-dir>/<post-slug>/ becomes
// public/blog/<post-slug>/<name>.webp, no wider than 1600px. Run it again
// after adding screenshots; it is idempotent.

import { promises as fs } from "node:fs";
import path from "node:path";
import sharp from "sharp";

const [, , inputDir] = process.argv;
if (!inputDir) {
  console.error("usage: node scripts/blog-images.mjs <input-dir>");
  process.exit(1);
}

const OUT_ROOT = path.join(process.cwd(), "public", "blog");
const MANIFEST = path.join(process.cwd(), "content", "blog", "images.ts");
const MAX_WIDTH = 1600;

async function* walk(dir) {
  for (const entry of await fs.readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(full);
    else if (/\.(png|jpe?g)$/i.test(entry.name)) yield full;
  }
}

for await (const file of walk(inputDir)) {
  const rel = path.relative(inputDir, file).replace(/\.(png|jpe?g)$/i, ".webp");
  const out = path.join(OUT_ROOT, rel);
  await fs.mkdir(path.dirname(out), { recursive: true });
  await sharp(file)
    .resize({ width: MAX_WIDTH, withoutEnlargement: true })
    .webp({ quality: 84 })
    .toFile(out);
  console.log("wrote", path.relative(process.cwd(), out));
}

// Manifest covers everything currently under public/blog, not just this run.
const sizes = {};
for await (const file of (async function* all(dir) {
  for (const entry of await fs.readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) yield* all(full);
    else if (/\.webp$/i.test(entry.name)) yield full;
  }
})(OUT_ROOT)) {
  const { width, height } = await sharp(file).metadata();
  sizes[`/blog/${path.relative(OUT_ROOT, file).split(path.sep).join("/")}`] = { width, height };
}

const entries = Object.keys(sizes)
  .sort()
  .map((key) => `  ${JSON.stringify(key)}: { width: ${sizes[key].width}, height: ${sizes[key].height} },`)
  .join("\n");
await fs.writeFile(
  MANIFEST,
  `// Generated by scripts/blog-images.mjs -- do not edit by hand.
// Pixel sizes of the images under public/blog, so next/image can reserve
// their space before they load. An image missing from here still renders,
// as a plain <img>, without the layout reservation.
export const BLOG_IMAGE_SIZES: Record<string, { width: number; height: number }> = {
${entries}
};
`,
);
console.log("manifest:", Object.keys(sizes).length, "images");
